[package]
name = "py-uesave"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "py_uesave"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.79"
pyo3 = "0.20.2"
uesave = { path = ".." }
